Add a simple string cast in order to prevent javascript to box values with just digits to integer instead of string. This prevents a TypeError: value.includes is not a function